### ISSUE TITLE
Is this project production ready?

### ISSUE THREAD

**Issue by simonfelding** [flux-subsystem-argo/flamingo#17]
Hi, great project! Is it ready for use in production or is there a milestone overview somewhere?

**Comment by simonfelding** [comment]
Brilliant. I thought the TF controller was a paid feature?

Sent from Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by chanwit** [comment]
The controller itself is free and opensource. But if you want the UI for the TF controller, [Weave GitOps OSS](https://github.com/weaveworks/weave-gitops) and Flamingo have a good enough view for viewing Terraform objects. 

We've recently launched enterprise support program for OSS components (including Flamingo support too), if you want our help to use them in production. Please see [Weave GitOps Assured program here](https://www.weave.works/product/gitops/). 

And [Weave GitOps Enterprise](https://www.weave.works/product/gitops-enterprise/) (the paid one) has a complete set of UIs for it including UI for dependency management plus many more (like Policy, Promotion Pipelines, Ephemeral GitOps Environments etc)

**Comment by simonfelding** [comment]
Very cool, thank you.

Sent from Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
