### ISSUE TITLE
[release process] kustomize build v2.5.16-fl.3-main-c4ce7dcc broken but 2.6 refs well

### ISSUE THREAD

**Issue by rosscdh** [flux-subsystem-argo/flamingo#19]
Trying to poke around with flux and argocd as both are good tools. Thanks for this effort!

```
kustomize build https://github.com/flux-subsystem-argo/flamingo//release\?ref\=v2.5.16-fl.3-main-c4ce7dcc
Error: git cmd = '/usr/bin/git fetch --depth=1 origin v2.5.16-fl.3-main-c4ce7dcc': exit status 128
```

but kz build https://github.com/flux-subsystem-argo/flamingo//release\?ref\=v2.6.7-fl.4-main-c4ce7dcc works..

is it an explicit mapping from flamingo to argo version? ie 2.5 must have flamingo 2.5?

**Comment by chanwit** [comment]
> is it an explicit mapping from flamingo to argo version? ie 2.5 must have flamingo 2.5?

exactly yes

While, we actively offer images for v2.4, v2.5 and v2.6, we offer the deployment YAML for v2.6 only.

**Comment by rosscdh** [comment]
No issue but the 2.5 version is currently not working.

Thanks

**Comment by chanwit** [comment]
Yes for v2.5, it requires a manual step.

Please download this file to your local machine: https://github.com/flux-subsystem-argo/flamingo/blob/main/release/kustomization.yaml
Then change it to v2.5 and image tag to v2.5.16-fl.3-main-c4ce7dcc

and apply it with kz manually.

**Comment by rosscdh** [comment]
Thanks will do.

PS got the instructions from here:
https://www.weave.works/blog/flamingo-expand-argo-cd-with-flux

**Comment by chanwit** [comment]
Thank you, @rosscdh!
Indeed, that was my piece of writing.

I will process the release process to address the scenario you've pointed out.

**Comment by chanwit** [comment]
We now changed the installation process to the new CLI. Please see `flamingo install` command.
