### ISSUE TITLE
Argo Lookup Causes Failure

### ISSUE THREAD

**Issue by reedjosh** [flux-subsystem-argo/flamingo#23]
We installed Flamingo to get the best of both worlds. Particularly the ability to use Helm's `lookup` function from Argo.

Unfortunately, Argo still attempts to template the helm chart and complains that the `lookup` object is missing and fails.

I would have thought Argo would skip templating and directly created Flux objects to do the work.

But no.

**Comment by reedjosh** [comment]
Closing as I just didn't have Flamingo fully installed. Only on the Front End.

**Comment by chanwit** [comment]
Hi @reedjosh

I'd love to learn about your use case. Could you share it a bit more please?

**Comment by reedjosh** [comment]
Hey, mostly we want to be able to refer to items within the cluster via Helm's `lookup` function.

But Argo just does a `helm template` so it doesn't actually run `lookup`.



Our use case is that we have several clusters and each have their own basic cluster information stored in them. If we can just use the `lookup` function, then we don't need cluster specific Helm values files.
