### ISSUE TITLE
Flamingo UI freezing on Sync, No-Op observed

### ISSUE THREAD

**Issue by allanadair** [flux-subsystem-argo/flamingo#27]
I have to apologize in advance for such a general issue with such a general question.

Background context:

My team has recently modified an existing ArgoCD deployment to use flamingo (v2.7.2-fl.6-main-b1742696). We have installed flux to the flux-system namespace, and when trying to use any of the new flamingo sync options for a flux-operated Application, we encounter problems. When selecting the "Apply Out Of Sync Only", "Use Flux Subsystem", "Auto-Create Flux Resources" we have experienced frozen user interfaces, various UI errors, and when dropping "Apply Out of Sync Only" in one experiment where several resources had been created, we experience a "no-op" (nothing happens at all). Using a network observation tool we have not uncovered any networking issues between ArgoCD and Flux. We have also not been able to detect any Events or error messages in ArgoCD pod/container logs.

So, we have a problem. Any hints on where to look to find what the specific problem is?

**Comment by chanwit** [comment]
We now have a new way to do so with the new CLI. Please refer to `flamingo generate-app` command.
