### ISSUE TITLE
"History and Rollback" does not list/disable correctly for OCIRepos

### ISSUE THREAD

**Issue by steve-fraser** [flux-subsystem-argo/flamingo#28]
![Screen Shot 2023-06-05 at 9 23 48 AM](https://github.com/flux-subsystem-argo/flamingo/assets/11997824/a3bbd7cd-1cca-4b65-b696-3741b43e5811)

**Comment by chanwit** [comment]
Thank yoou @steve-fraser 
We would mark this as unsupported feature for now.

I'll take a look on how to link the concept of rollback from ArgoCD to Flamingo

**Comment by chanwit** [comment]
We decided to not support this right now. Please re-open if you want to further discuss this use case.
