### ISSUE TITLE
What's the open source license for this project? 

### ISSUE THREAD

**Issue by haiwu** [flux-subsystem-argo/flamingo#29]
I could not find any open source license for this project. Flux2 has 'Apache-2.0' license on its Github page. 

Could you please clarify? Wondering if it would be ok to use this open source project ...

**Comment by haiwu** [comment]
@chanwit ?

**Comment by chanwit** [comment]
Hi @haiwu 

The code repository is here: https://github.com/flux-subsystem-argo/fsa
And the code license is same as that of Flux, which is Apache 2.0: https://github.com/flux-subsystem-argo/fsa/blob/main/LICENSE

**Comment by haiwu** [comment]
Aha, thanks for confirming this @chanwit! I am confused still, as I could not find the OSS license for this repository 'https://github.com/flux-subsystem-argo/flamingo'. 

What's the main difference between 'https://github.com/flux-subsystem-argo/fsa' and 'https://github.com/flux-subsystem-argo/flamingo'?

**Comment by chanwit** [comment]
The FSA is the code and patch repository, while the Flamingo (this one) is the demo (YAML stuff) and landing repository (the home page in a sense). 

Users usually report problems here in this repo, so it acts like the contact point of the project.

**Comment by chanwit** [comment]
I shall close this one. Please feel free to re-open it if you have further questions.
