### ISSUE TITLE
Change deployment name "demo"

### ISSUE THREAD

**Issue by clayrisser** [flux-subsystem-argo/flamingo#30]
Is it possible to change the deployment name from "demo" to something that sounds more production ready. Even if it is stable, it scares people.

**Comment by chanwit** [comment]
I'm working on a CLI to make the installation process more streamlined. The new CLI is expected to be released very soon.

**Comment by chanwit** [comment]
The CLI has been released.
The instructions on this repository are now CLI-based and we'll move the demo to another repo soon.
