### ISSUE TITLE
Login page not shown

### ISSUE THREAD

**Issue by clayrisser** [flux-subsystem-argo/flamingo#31]
After setting this up, I portforwarded the argo server and I was surprised to see there was no authentication. Is this normal, if so shouldn't the instructions mentioning the login page be removed?

**Comment by chanwit** [comment]
The current setup enables the anonymous mode by default but you can click the Login link to show the Login page.

**Comment by chanwit** [comment]
Now with `flamingo install` you'll see the Login page normally. The install command comes with `--anonymous` flag for the case that you want to enable the anonymous UI similar to the demo in this repo.
