### ISSUE TITLE
ArgoCD 2.8 release

### ISSUE THREAD

**Issue by adberger** [flux-subsystem-argo/flamingo#36]
Hey there

Any intentions to publish flamingo with ArgoCD 2.8 (currently 2.8.4) baked in?
I saw that there is a pre-release (https://github.com/flux-subsystem-argo/flamingo/releases/tag/v2.8.0-rc6-fl.15-main-da46678f).

**Comment by chanwit** [comment]
we changed the installation process to be CLI-based now.

Please try installing the Flamingo CLI, and

```
flamingo list-candidates
```
You would see the v2.8.3 image there.

Yep, v2.8.4 is scheduled to be released this week.

**Comment by chanwit** [comment]
Flamingo v2.8.4 is ready for testing. It will be promoted to the stable one soon after tested.

```
❯ flamingo list-candidates --dev
FLAMINGO     FSA-IMAGE                     SUPPORTED FLUX
v2.8.4-dev   v2.8.4-fl.21-main-6c72e98c    v2.1.0
v2.8.3       v2.8.3-fl.21-main-3155e06d    v2.1.0
v2.8.1       v2.8.1-fl.21-main-7242d1b4    v2.1.0
v2.7.14      v2.7.14-fl.15-main-79945e4b   v2.0.1
v2.7.12      v2.7.12-fl.15-main-1072aa5e   v2.0.1
v2.8.0       v2.8.0-fl.15-main-aef83705    v2.0.1
v2.7.11      v2.7.11-fl.15-main-32b9702c   v2.0.1
v2.6.15      v2.6.15-fl.15-main-10ea1bf3   v2.0.1
v2.6.14      v2.6.14-fl.15-main-e9a0660c   v2.0.1
v2.5.22      v2.5.22-fl.12-main-0f9b4dbc   v0.41.2
```

**Comment by adberger** [comment]
I see, thanks :)
