### ISSUE TITLE
recommended way to deploy on existing cluster

### ISSUE THREAD

**Issue by joaocc** [flux-subsystem-argo/flamingo#40]
Hi,
Where can I find the recommendations of install sequences of flux2, argocd and flamingo for:
* new clusters 
* clusters that already have flux2 and we want to deploy flamingo+argo?
Also, are flux v2.1.x+ CRDs supported?
Thanks

**Comment by chanwit** [comment]
1. In case of new cluster, you can follow the following steps: https://github.com/flux-subsystem-argo/cli#getting-started-with-flamingo-cli
2. To replace ArgoCD with Flamingo, please refer to this Kustomization file: https://github.com/flux-subsystem-argo/flamingo/blob/main/release/kustomization.yaml
3. If you want to install Flamingo in a namespace tenant to make it not interfere with your existing ArgoCD installation, we'll support it very soon.
4. Yep, we support and tested Flamingo v2.8.4 against Flux 2.1.x.

**Comment by joaocc** [comment]
Thx for the reply.
We are still assessing both ArgoCD and Flamingo, and I had the impression Flamingo would be installed on top of ArgoCD (or side by side) and not replace (as seems to be intended by point 2 above). Could you please pointers for archtitecture/design docs where I can get a better grasp of that?
Thx

**Comment by chanwit** [comment]
> I had the impression Flamingo would be installed on top of ArgoCD

Flamingo offers a patched version for each ArgoCD binary. Please think of it as OpenShift which is built on top of Kubernetes for example. You can install and use Flamingo normally just like ArgoCD. The Flux Subsystem is activated only if you tick "FluxSubSystem" in the sync options.

Maybe this blog post would help: https://www.weave.works/blog/get-started-flamingo-flux-cd-subsystem-for-argo-cd

**Comment by joaocc** [comment]
Thanks. While I understand the point better and the approach (and as a long time flux2 user), I think the article fails to be clear on the fact that it doesn't work with a standard ArgoCD deployment ("It is an enhanced version of Argo CD with the Flux CD sub-system built-in").
The fact that it is described as a "Flux Subsystem for Argo" even furthers the confusion, as a subsystem for something is not, by definition, a replacement of that something.
Please note that I am not questioning the approach, but rather the way it is presented.
Prob this has been discussed in the past, but are there any plans to get FSA as part of the standard ArgoCD, or if ArgoCD supports the approach used by the FSA?
This would be important in understanding the longevity and risk of a bridge approach between both amazing tools.
Thanks

**Comment by joaocc** [comment]
Thank you for the clarification.

**Comment by joaocc** [comment]
Still regarding the above point, I can only root for a healthy and productive exchange of ideas between the flux/flamingo and ArgoCD teams :)

**Comment by joaocc** [comment]
With regards to my original question, and now that I have understood a bit more of the context, is it possible to deploy Flamingo via helm chart?
Our current environment sets up EKS clusters via terraform, and installs flux2 via helm (separate from bootstrapping), as well as installing most other components via helm (managed by terraform or by flux2). Being able to install flamingo by helm would fit nicely into this picture of pre-gitops setup.
Thx

**Comment by chanwit** [comment]
We don't have our own Helm Chart at the moment but we can add one.

**Comment by joaocc** [comment]
That would be great! Even if you don't have time create a full helm chart, it would be nice to understand some alternatives are possible. I was wondering whether we could deploy the standard ArgoCD charts (https://github.com/argoproj/argo-helm/tree/main/charts/argo-cd), and replace some images with the corresponding patched ones, or if there are more customisations required for a minimal baseline install. 
Thanks

**Comment by chanwit** [comment]
About to mention that.

It would work for sure. A KubeCon demo presented by Weaveworks and Microsoft a couple days ago used the chart with Flamingo image.

**Comment by chanwit** [comment]
I shall close this as there's no action for us to implement Helm chart on our side anytime soon.
