### ISSUE TITLE
web installer fails on images without sudo

### ISSUE THREAD

**Issue by joaocc** [flux-subsystem-argo/flamingo#41]
Installing on debian image without sudo fails with error.
This seems to be due to 
```sh
        eval "sudo ${CMD_MOVE}"
```

**Comment by chanwit** [comment]
You could choose to install it on a local bin dir without `sudo`:

https://github.com/flux-subsystem-argo/flamingo/blob/ef02f00f17000b5a95bee67abcd6387819e942be/install/flamingo.sh#L219-L223
