### ISSUE TITLE
Add docs about installing Flamingo via a HelmRelease and a Helm chart

### ISSUE THREAD

**Issue by chanwit** [flux-subsystem-argo/flamingo#48]

**Comment by berlincount** [comment]
Running into the same problem - did you manage to do it?

**Comment by worawatwi** [comment]
Please advise how to install via HelmRelease.

**Comment by chanwit** [comment]
Added to README: https://github.com/flux-subsystem-argo/flamingo?tab=readme-ov-file#install-flamingo-with-helmrelease
