### ISSUE TITLE
Argocd-server unknown command

### ISSUE THREAD

**Issue by david13childs** [flux-subsystem-argo/flamingo#49]
I've followed the instructions here https://www.weave.works/blog/flamingo-expand-argo-cd-with-flux

For argocd version 2.4.15 (helm chart 5.6.1).

Since the version stated in the documentation is not available. 

Now argocd-server pod crash loops.

Error: unknown command "/usr/local/bin/argocd-server" for "argocd-server"
Run 'argocd-server --help' for usage.

Image
ghcr.io/flux-subsystem-argo/fsa/argocd:v2.4.12-fl.2-main-d68e6cb8

**Comment by chanwit** [comment]
Hi @david13childs 

Sorry that the versions we are currently supporting are v2.7, 2.8 and 2.9.

**Comment by david13childs** [comment]
Thanks for the quick response.  I'll look at updating my argocd.  Would be
nice if you could have whoever maintains that documentation update the
page, I've broken my dev deploys and that will probably end my manager's
interest in flamingo, thus weaveworks.

**Comment by kingdonb** [comment]
Thanks for the feedback David, we are interested in resolving it for you.

Sorry about your bad experience with Weaveworks.
