### ISSUE TITLE
Future of Flamingo project

### ISSUE THREAD

**Issue by demisx** [flux-subsystem-argo/flamingo#50]
Hi. I’m reading that Weaveworks, this project sponsor, is shutting down and had to lay off its employees in Dec 2023. Or, at least, most of them. How’s this reflect on the future of the Flamingo project? Can we still count on it being actively supported. Thank you.

**Comment by chanwit** [comment]
Hi @demisx 

Despite WW shutdown, I'm, not very actively, but still maintaining Flamingo.
For the future direction of this project, I'm working on it. Please stay tuned.

**Comment by chanwit** [comment]
FYI, Flamingo v0.8.2 has been released to support Flux v2.2.3.
