### ISSUE TITLE
HelmRelease don't display underlying resources 

### ISSUE THREAD

**Issue by pmialon** [flux-subsystem-argo/flamingo#53]
Hi,

We use Flux v2.2.3 and Flamingo v0.8.2.

We only use helm.toolkit.fluxcd.io/v2beta2.

Previously, the HelmRelease displayed the state of the resources it created in the user interface, but now we only have the state of the HelmRelease.

I don't see anything relevant in the ArgoCD logs, everything seems to be going well. 

Is this a bad configuration on our part or a new behaviour?

Regards,

**Comment by chanwit** [comment]
Thank you for reporting @pmialon 
Could you also paste the Flamingo image tag you're using?

**Comment by chanwit** [comment]
fixed in `v2.9.6-fl.22-main-402c9e49`

**Comment by chanwit** [comment]
@pmialon please feel free to re-open this issue if the problem still persists.

**Comment by pmialon** [comment]
Thanks a lot it worked!!!
Have a good WE.
